---
- name: Install Nginx on the server
  hosts: all
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx is started and enabled on boot
      systemd:
        name: nginx
        enabled: yes
        state: started

    - name: Allow HTTP and HTTPS traffic through the firewall (UFW)
      ufw:
        rule: allow
        name: 'Nginx Full'
        state: enabled
